print.jnt <- function(x, digits = 4, ...){
  cat("\n")
  cat("Johnson-Neyman Technique\n")
  cat("\n")
  cat("Alpha = ", x$alpha, "\n")
  cat("\n")
  cat("Set 1:\n")
  cat("\tSlope\t\t", format(x$slope1, digits = digits), "\n")
  cat("\tIntercept\t", format(x$int1, digits = digits), "\n")
  cat("\n")
  cat("Set 2:\n")
  cat("\tSlope\t\t", format(x$slope2, digits = digits), "\n")
  cat("\tIntercept\t", format(x$int2, digits = digits), "\n")
  cat("\n")
  cat("Region of non-significant slope difference\n")
  cat("\tLower\t\tUpper\n")
  cat("\t", format(x$lower, digits = digits), "\t", format(x$upper, digits = digits), "\n\n")
}